# Generated by Django 2.2.12 on 2020-10-04 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20201001_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='도시명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '도시',
                'verbose_name_plural': '도시',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시물', 'verbose_name_plural': '게시물'},
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.DateField(auto_now=True, verbose_name='예상 종료 날짜'),
        ),
        migrations.AddField(
            model_name='post',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='즐겨찾기 수'),
        ),
        migrations.AddField(
            model_name='post',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_users', to=settings.AUTH_USER_MODEL, verbose_name='즐겨찾기한 사람들'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.DateField(auto_now=True, verbose_name='시작 날짜'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('hiring', '모집 중'), ('end', '모집 완료')], default='hiring', max_length=32, verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='연락처'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='지역명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='service.City', verbose_name='도시')),
            ],
            options={
                'verbose_name': '세부지역',
                'verbose_name_plural': '세부지역',
            },
        ),
    ]
