# Generated by Django 2.2.12 on 2020-10-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hire_limit',
            field=models.PositiveIntegerField(null=True, verbose_name='모집인원'),
        ),
    ]
